#!/bin/bash

mkdir /usr/share/arduino/libraries/Module
mkdir /usr/share/arduino/libraries/BrushlessDCMotor
mkdir /usr/share/arduino/libraries/DepthSensor

cp Module.cpp Module.h /usr/share/arduino/libraries/Module
cp BrushlessDCMotor.cpp BrushlessDCMotor.h /usr/share/arduino/libraries/BrushlessDCMotor
cp DepthSensor.cpp DepthSensor.h /usr/share/arduino/libraries/DepthSensor
